-- Server-owned support tables for retailer administration and the QuickBooks
-- customer cache. Browsers never receive service-role access to these tables.

create table if not exists public.portal_admin_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid not null,
  actor_org text,
  action text not null,
  target_id uuid,
  target_email text,
  target_org text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.portal_admin_audit enable row level security;
revoke all on table public.portal_admin_audit from anon, authenticated;
grant all on table public.portal_admin_audit to service_role;

create table if not exists public.quickbooks_customer_cache (
  quickbooks_customer_id text primary key,
  display_name text not null,
  company_name text,
  active boolean not null default true,
  balance numeric,
  balance_with_jobs numeric,
  currency text,
  parent_customer_id text,
  email text,
  billing_city text,
  source_updated_at timestamptz,
  synced_at timestamptz not null default now(),
  raw jsonb not null default '{}'::jsonb
);

create table if not exists public.quickbooks_customer_link (
  quickbooks_customer_id text primary key references public.quickbooks_customer_cache(quickbooks_customer_id) on delete cascade,
  portal_status text not null default 'NOT YET QUALIFIED',
  location_count integer not null default 0 check (location_count >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.quickbooks_sync_state (
  id smallint primary key check (id = 1),
  realm_id text,
  refresh_token text,
  status text not null default 'never',
  last_started_at timestamptz,
  last_successful_at timestamptz,
  last_error text,
  customer_count integer,
  updated_at timestamptz not null default now()
);

insert into public.quickbooks_sync_state (id) values (1) on conflict (id) do nothing;

alter table public.quickbooks_customer_cache enable row level security;
alter table public.quickbooks_customer_link enable row level security;
alter table public.quickbooks_sync_state enable row level security;

revoke all on table public.quickbooks_customer_cache from anon, authenticated;
revoke all on table public.quickbooks_customer_link from anon, authenticated;
revoke all on table public.quickbooks_sync_state from anon, authenticated;
grant all on table public.quickbooks_customer_cache to service_role;
grant all on table public.quickbooks_customer_link to service_role;
grant all on table public.quickbooks_sync_state to service_role;

comment on table public.quickbooks_customer_cache is
  'Read-only server cache of QuickBooks Customer records. QuickBooks remains authoritative.';
comment on table public.quickbooks_customer_link is
  'Portal-specific readiness and store count linked by a namespaced QuickBooks customer id.';
comment on table public.portal_admin_audit is
  'Server-side record of user invitations, role changes, scope changes, and deactivations.';
