-- Durable portal orders. Monday remains the work-management destination, but
-- the portal owns the customer-facing order record and event history so an
-- accepted order survives refreshes and cannot be changed only in a browser.

create table if not exists public.portal_order (
  id uuid primary key default gen_random_uuid(),
  client_request_id uuid not null unique,
  portal_reference text not null unique,
  order_number text,
  monday_item_id text,
  monday_board_id text,
  organization text not null,
  location_license text not null references public.portal_store(license_number),
  location_name text not null,
  submitted_by uuid references auth.users(id) on delete set null,
  submitted_by_email text,
  submitted_by_role text not null check (submitted_by_role in ('owner', 'buyer', 'internal')),
  state text not null check (state in (
    'awaiting_owner_approval', 'ordered', 'approved', 'processed',
    'delivered', 'declined', 'canceled', 'exception'
  )),
  workflow_state text not null default 'pending' check (workflow_state in (
    'pending', 'accepted', 'needs_reconciliation', 'rejected'
  )),
  workflow_error text,
  owner_approval_required boolean not null default false,
  approval_threshold_cents integer check (approval_threshold_cents is null or approval_threshold_cents >= 0),
  order_value_cents integer not null check (order_value_cents >= 0),
  contains_preorder boolean not null default false,
  release_hold boolean not null default false,
  delivery_window text,
  receiving_contact text,
  receiving_instructions text,
  metadata jsonb not null default '{}'::jsonb,
  submitted_at timestamptz not null default now(),
  accepted_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists portal_order_order_number_idx
  on public.portal_order (order_number) where order_number is not null;
create unique index if not exists portal_order_monday_item_idx
  on public.portal_order (monday_item_id) where monday_item_id is not null;
create index if not exists portal_order_org_created_idx
  on public.portal_order (organization, submitted_at desc);
create index if not exists portal_order_store_created_idx
  on public.portal_order (location_license, submitted_at desc);
create index if not exists portal_order_workflow_idx
  on public.portal_order (workflow_state, updated_at desc);

create table if not exists public.portal_order_line (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.portal_order(id) on delete cascade,
  line_number integer not null check (line_number > 0),
  product_id text not null,
  product_name text not null,
  sku text,
  compliance_tag text,
  quantity integer not null check (quantity > 0 and quantity <= 9999),
  unit text not null default 'each' check (unit in ('each', 'gram')),
  unit_price_cents integer not null check (unit_price_cents >= 0),
  line_total_cents integer not null check (line_total_cents >= 0),
  order_mode text not null default 'standard' check (order_mode in ('standard', 'preorder')),
  release_state text not null default 'released' check (release_state in ('released', 'awaiting_release')),
  created_at timestamptz not null default now(),
  unique (order_id, line_number)
);

create index if not exists portal_order_line_product_idx
  on public.portal_order_line (product_id);

create table if not exists public.portal_order_event (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.portal_order(id) on delete cascade,
  source text not null check (source in ('portal-intake', 'store-owner', 'store-user', 'internal', 'monday', 'system')),
  from_state text,
  to_state text not null,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text,
  raw_status text,
  note text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists portal_order_event_order_idx
  on public.portal_order_event (order_id, created_at asc);

create table if not exists public.portal_order_sync_outbox (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.portal_order(id) on delete cascade,
  event_id uuid not null references public.portal_order_event(id) on delete cascade,
  target text not null default 'monday' check (target = 'monday'),
  state text not null default 'pending' check (state in ('pending', 'sent', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  last_attempt_at timestamptz,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (event_id, target)
);

create index if not exists portal_order_sync_outbox_pending_idx
  on public.portal_order_sync_outbox (state, created_at asc);

alter table public.portal_order enable row level security;
alter table public.portal_order_line enable row level security;
alter table public.portal_order_event enable row level security;
alter table public.portal_order_sync_outbox enable row level security;

revoke all on table public.portal_order from anon, authenticated;
revoke all on table public.portal_order_line from anon, authenticated;
revoke all on table public.portal_order_event from anon, authenticated;
revoke all on table public.portal_order_sync_outbox from anon, authenticated;
grant all on table public.portal_order to service_role;
grant all on table public.portal_order_line to service_role;
grant select, insert on table public.portal_order_event to service_role;
grant all on table public.portal_order_sync_outbox to service_role;

create or replace function public.portal_create_order(
  p_client_request_id uuid,
  p_portal_reference text,
  p_organization text,
  p_location_license text,
  p_location_name text,
  p_submitted_by uuid,
  p_submitted_by_email text,
  p_submitted_by_role text,
  p_state text,
  p_owner_approval_required boolean,
  p_approval_threshold_cents integer,
  p_order_value_cents integer,
  p_contains_preorder boolean,
  p_release_hold boolean,
  p_delivery_window text,
  p_receiving_contact text,
  p_receiving_instructions text,
  p_lines jsonb,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  created_order_id uuid;
  existing_order public.portal_order%rowtype;
  computed_order_value_cents bigint;
  request_fingerprint text;
begin
  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) < 1 or jsonb_array_length(p_lines) > 250 then
    raise exception 'An order must contain between one and 250 lines';
  end if;

  select coalesce(sum((line.value ->> 'lineTotalCents')::bigint), 0)
  into computed_order_value_cents
  from jsonb_array_elements(p_lines) as line(value);

  if computed_order_value_cents <> p_order_value_cents then
    raise exception 'The order value does not match its verified lines';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_lines) as line(value)
    where (line.value ->> 'lineTotalCents')::bigint
      <> (line.value ->> 'quantity')::bigint * (line.value ->> 'unitPriceCents')::bigint
  ) then
    raise exception 'An order line total is invalid';
  end if;

  request_fingerprint := md5(jsonb_build_object(
    'portalReference', trim(p_portal_reference),
    'organization', p_organization,
    'locationLicense', p_location_license,
    'submittedBy', p_submitted_by,
    'submittedByRole', p_submitted_by_role,
    'state', p_state,
    'orderValueCents', p_order_value_cents,
    'deliveryWindow', p_delivery_window,
    'receivingContact', p_receiving_contact,
    'receivingInstructions', p_receiving_instructions,
    'lines', p_lines
  )::text);

  insert into public.portal_order (
    client_request_id, portal_reference, organization, location_license,
    location_name, submitted_by, submitted_by_email, submitted_by_role,
    state, owner_approval_required, approval_threshold_cents,
    order_value_cents, contains_preorder, release_hold, delivery_window,
    receiving_contact, receiving_instructions, metadata
  ) values (
    p_client_request_id, trim(p_portal_reference), p_organization,
    p_location_license, p_location_name, p_submitted_by,
    nullif(trim(coalesce(p_submitted_by_email, '')), ''), p_submitted_by_role,
    p_state, p_owner_approval_required, p_approval_threshold_cents,
    p_order_value_cents, p_contains_preorder, p_release_hold,
    nullif(trim(coalesce(p_delivery_window, '')), ''),
    nullif(trim(coalesce(p_receiving_contact, '')), ''),
    nullif(trim(coalesce(p_receiving_instructions, '')), ''),
    coalesce(p_metadata, '{}'::jsonb) || jsonb_build_object('_requestFingerprint', request_fingerprint)
  )
  on conflict (client_request_id) do nothing
  returning id into created_order_id;

  if created_order_id is null then
    select * into existing_order
    from public.portal_order
    where client_request_id = p_client_request_id;
    if existing_order.metadata ->> '_requestFingerprint' is distinct from request_fingerprint then
      raise exception 'The idempotency identifier belongs to a different verified order';
    end if;
    return jsonb_build_object(
      'id', existing_order.id,
      'created', false,
      'workflowState', existing_order.workflow_state,
      'orderNumber', existing_order.order_number,
      'portalReference', existing_order.portal_reference,
      'state', existing_order.state
    );
  end if;

  insert into public.portal_order_line (
    order_id, line_number, product_id, product_name, sku, compliance_tag,
    quantity, unit, unit_price_cents, line_total_cents, order_mode, release_state
  )
  select
    created_order_id,
    line.ordinality::integer,
    trim(line.value ->> 'productId'),
    trim(line.value ->> 'product'),
    nullif(trim(coalesce(line.value ->> 'sku', '')), ''),
    nullif(trim(coalesce(line.value ->> 'tag', '')), ''),
    (line.value ->> 'quantity')::integer,
    coalesce(nullif(trim(line.value ->> 'unit'), ''), 'each'),
    (line.value ->> 'unitPriceCents')::integer,
    (line.value ->> 'lineTotalCents')::integer,
    coalesce(nullif(trim(line.value ->> 'orderMode'), ''), 'standard'),
    coalesce(nullif(trim(line.value ->> 'releaseState'), ''), 'released')
  from jsonb_array_elements(p_lines) with ordinality as line(value, ordinality);

  insert into public.portal_order_event (
    order_id, source, from_state, to_state, actor_id, actor_email, note, metadata
  ) values (
    created_order_id, 'portal-intake', null, p_state, p_submitted_by,
    nullif(trim(coalesce(p_submitted_by_email, '')), ''),
    'Order verified and submitted to the portal intake.',
    jsonb_build_object('clientRequestId', p_client_request_id)
  );

  return jsonb_build_object(
    'id', created_order_id,
    'created', true,
    'workflowState', 'pending',
    'orderNumber', null,
    'portalReference', trim(p_portal_reference),
    'state', p_state
  );
end;
$$;

create or replace function public.portal_mark_order_workflow(
  p_order_id uuid,
  p_workflow_state text,
  p_order_number text default null,
  p_monday_item_id text default null,
  p_monday_board_id text default null,
  p_error text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  changed public.portal_order%rowtype;
begin
  if p_workflow_state not in ('pending', 'accepted', 'needs_reconciliation', 'rejected') then
    raise exception 'Unsupported workflow state';
  end if;

  update public.portal_order
  set workflow_state = p_workflow_state,
      order_number = case when p_workflow_state = 'accepted' then nullif(trim(coalesce(p_order_number, '')), '') else order_number end,
      monday_item_id = coalesce(nullif(trim(coalesce(p_monday_item_id, '')), ''), monday_item_id),
      monday_board_id = coalesce(nullif(trim(coalesce(p_monday_board_id, '')), ''), monday_board_id),
      workflow_error = nullif(trim(coalesce(p_error, '')), ''),
      accepted_at = case when p_workflow_state = 'accepted' then coalesce(accepted_at, now()) else accepted_at end,
      metadata = metadata || coalesce(p_metadata, '{}'::jsonb),
      updated_at = now()
  where id = p_order_id
  returning * into changed;

  if not found then raise exception 'Portal order not found'; end if;

  if p_workflow_state = 'accepted' then
    insert into public.portal_order_event (
      order_id, source, from_state, to_state, raw_status, note, metadata
    ) values (
      changed.id, 'system', changed.state, changed.state, 'workflow_accepted',
      'Monday accepted the portal order intake.', coalesce(p_metadata, '{}'::jsonb)
    );
  end if;

  return jsonb_build_object(
    'id', changed.id,
    'workflowState', changed.workflow_state,
    'orderNumber', changed.order_number,
    'mondayItemId', changed.monday_item_id,
    'state', changed.state
  );
end;
$$;

create or replace function public.portal_apply_order_transition(
  p_order_id uuid,
  p_expected_state text,
  p_target_state text,
  p_actor_id uuid,
  p_actor_email text,
  p_source text,
  p_note text default null,
  p_raw_status text default null,
  p_metadata jsonb default '{}'::jsonb,
  p_release_hold boolean default null,
  p_enqueue_monday boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_order public.portal_order%rowtype;
  created_event_id uuid;
begin
  select * into current_order
  from public.portal_order
  where id = p_order_id
  for update;

  if not found then raise exception 'Portal order not found'; end if;
  if current_order.state <> p_expected_state then raise exception 'Order state changed; refresh before trying again'; end if;
  if p_source not in ('store-owner', 'store-user', 'internal', 'monday', 'system') then raise exception 'Unsupported order event source'; end if;

  update public.portal_order
  set state = p_target_state,
      release_hold = coalesce(p_release_hold, release_hold),
      updated_at = now()
  where id = p_order_id;

  insert into public.portal_order_event (
    order_id, source, from_state, to_state, actor_id, actor_email,
    raw_status, note, metadata
  ) values (
    p_order_id, p_source, p_expected_state, p_target_state, p_actor_id,
    nullif(trim(coalesce(p_actor_email, '')), ''),
    nullif(trim(coalesce(p_raw_status, '')), ''),
    nullif(trim(coalesce(p_note, '')), ''),
    coalesce(p_metadata, '{}'::jsonb)
  ) returning id into created_event_id;

  if p_enqueue_monday then
    insert into public.portal_order_sync_outbox (order_id, event_id)
    values (p_order_id, created_event_id)
    on conflict (event_id, target) do nothing;
  end if;

  return jsonb_build_object(
    'orderId', p_order_id,
    'eventId', created_event_id,
    'fromState', p_expected_state,
    'toState', p_target_state,
    'releaseHold', coalesce(p_release_hold, current_order.release_hold),
    'syncQueued', p_enqueue_monday
  );
end;
$$;

revoke all on function public.portal_create_order(uuid, text, text, text, text, uuid, text, text, text, boolean, integer, integer, boolean, boolean, text, text, text, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.portal_mark_order_workflow(uuid, text, text, text, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.portal_apply_order_transition(uuid, text, text, uuid, text, text, text, text, jsonb, boolean, boolean) from public, anon, authenticated;
grant execute on function public.portal_create_order(uuid, text, text, text, text, uuid, text, text, text, boolean, integer, integer, boolean, boolean, text, text, text, jsonb, jsonb) to service_role;
grant execute on function public.portal_mark_order_workflow(uuid, text, text, text, text, text, jsonb) to service_role;
grant execute on function public.portal_apply_order_transition(uuid, text, text, uuid, text, text, text, text, jsonb, boolean, boolean) to service_role;

comment on table public.portal_order is
  'Authoritative customer-facing portal order header. Monday remains the downstream work-management destination.';
comment on table public.portal_order_line is
  'Server-verified order lines with the accepted store price and release mode preserved at submission.';
comment on table public.portal_order_event is
  'Append-only order state history attributed to the portal, retailer, workforce, Monday, or system.';
comment on table public.portal_order_sync_outbox is
  'Retryable portal-to-Monday status synchronization queue. A failed downstream update never erases the portal transition.';
