-- Close the order/sync races at their database boundaries. Portal
-- commitments are separate from Canix reservations: they represent accepted
-- portal demand until an order is declined, canceled, delivered, enters a
-- legacy exception state, or is rejected by the downstream intake workflow.

create table if not exists public.portal_inventory_commitment (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.portal_order(id) on delete cascade,
  product_id text not null check (product_id ~ '^canix:item:[1-9][0-9]*$'),
  quantity integer not null check (quantity > 0),
  active boolean not null default true,
  committed_at timestamptz not null default now(),
  released_at timestamptz,
  unique (order_id, product_id)
);

create index if not exists portal_inventory_commitment_active_product_idx
  on public.portal_inventory_commitment (product_id)
  where active;

alter table public.portal_inventory_commitment enable row level security;
revoke all on table public.portal_inventory_commitment from anon, authenticated;
grant all on table public.portal_inventory_commitment to service_role;
grant usage, select on sequence public.portal_inventory_commitment_id_seq to service_role;

alter table public.portal_order
  add column if not exists canix_sales_order_id bigint;

create unique index if not exists portal_order_canix_sales_order_idx
  on public.portal_order (canix_sales_order_id)
  where canix_sales_order_id is not null;

create or replace function public.portal_commit_order_line_inventory()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_run_id uuid;
  item_id_value bigint;
  available_units numeric;
  already_committed numeric;
  line_group record;
begin
  if exists (
    select 1 from inserted_lines
    where unit <> 'each' or product_id !~ '^canix:item:[1-9][0-9]*$'
  ) then
    raise exception 'Live portal orders require count-based Canix catalog items';
  end if;

  select last_successful_run_id into current_run_id
  from public.canix_sync_state
  where id = 1;
  if current_run_id is null then
    raise exception 'No successful Canix snapshot is available';
  end if;

  for line_group in
    select order_id, product_id, sum(quantity)::integer as requested_quantity
    from inserted_lines
    group by order_id, product_id
    order by product_id, order_id
  loop
    -- Every order touching one product takes the same transaction-scoped lock,
    -- in deterministic product order, so verification and commitment cannot
    -- interleave or deadlock across a multi-line insert.
    perform pg_advisory_xact_lock(hashtextextended(line_group.product_id, 0));
    item_id_value := substring(line_group.product_id from '^canix:item:([0-9]+)$')::bigint;

    select coalesce(sum(greatest(coalesce(orderable_units, weight, 0), 0)), 0)
    into available_units
    from public.canix_package_current
    where sync_run_id = current_run_id
      and item_id = item_id_value
      and quantity_type = 'CountBased'
      and status_category = 'available'
      and greatest(coalesce(orderable_units, weight, 0), 0) > 0
      and regexp_replace(lower(coalesce(test_result_status, lab_test_status, '')), '[^a-z0-9]+', '', 'g') <> 'testfailed';

    -- A portal commitment is counted only for the quantity not yet covered by
    -- the specific Canix sales order linked to that portal order. Unrelated
    -- Canix allocations still reduce available_units and can never satisfy a
    -- portal commitment.
    select coalesce(sum(greatest(commitment.quantity - coalesce(coverage.allocated_units, 0), 0)), 0)
    into already_committed
    from public.portal_inventory_commitment commitment
    join public.portal_order orders on orders.id = commitment.order_id
    left join lateral (
      select coalesce(sum(greatest(coalesce(package.weight, 0), 0)), 0) as allocated_units
      from public.canix_package_current package
      where package.sync_run_id = current_run_id
        and package.item_id = item_id_value
        and package.quantity_type = 'CountBased'
        and package.status_category = 'allocated'
        and package.sales_order_id = orders.canix_sales_order_id
        and regexp_replace(lower(coalesce(package.test_result_status, package.lab_test_status, '')), '[^a-z0-9]+', '', 'g') <> 'testfailed'
    ) coverage on orders.canix_sales_order_id is not null
    where commitment.product_id = line_group.product_id and commitment.active;

    if line_group.requested_quantity > available_units - already_committed then
      raise exception 'Requested quantity exceeds Canix availability after active portal commitments';
    end if;

    insert into public.portal_inventory_commitment (order_id, product_id, quantity)
    values (line_group.order_id, line_group.product_id, line_group.requested_quantity)
    on conflict (order_id, product_id) do update
    set quantity = public.portal_inventory_commitment.quantity + excluded.quantity,
        active = true,
        released_at = null;
  end loop;

  return null;
end;
$$;

drop trigger if exists portal_order_line_inventory_commitment on public.portal_order_line;
create trigger portal_order_line_inventory_commitment
after insert on public.portal_order_line
referencing new table as inserted_lines
for each statement execute function public.portal_commit_order_line_inventory();

create or replace function public.portal_release_terminal_inventory_commitments()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.state in ('delivered', 'declined', 'canceled', 'exception')
    or new.workflow_state = 'rejected' then
    update public.portal_inventory_commitment
    set active = false,
        released_at = coalesce(released_at, now())
    where order_id = new.id and active;
  end if;
  return new;
end;
$$;

drop trigger if exists portal_order_release_inventory_commitment on public.portal_order;
create trigger portal_order_release_inventory_commitment
after update of state, workflow_state on public.portal_order
for each row execute function public.portal_release_terminal_inventory_commitments();

create or replace function public.portal_enforce_order_transition_graph()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.state is not distinct from old.state then return new; end if;
  if not (
    (old.state = 'awaiting_owner_approval' and new.state in ('ordered', 'declined'))
    or (old.state = 'ordered' and new.state in ('approved', 'canceled'))
    or (old.state = 'approved' and new.state in ('processed', 'canceled'))
    or (old.state = 'processed' and new.state = 'delivered')
  ) then
    raise exception 'Unsupported portal order transition from % to %', old.state, new.state;
  end if;
  return new;
end;
$$;

drop trigger if exists portal_order_transition_graph on public.portal_order;
create trigger portal_order_transition_graph
before update of state on public.portal_order
for each row execute function public.portal_enforce_order_transition_graph();

-- Preserve demand from any active orders created before this migration.
insert into public.portal_inventory_commitment (order_id, product_id, quantity, active, committed_at)
select line.order_id, line.product_id, sum(line.quantity)::integer, true, min(line.created_at)
from public.portal_order_line line
join public.portal_order orders on orders.id = line.order_id
where line.product_id ~ '^canix:item:[1-9][0-9]*$'
  and line.unit = 'each'
  and orders.state not in ('delivered', 'declined', 'canceled', 'exception')
  and orders.workflow_state <> 'rejected'
group by line.order_id, line.product_id
on conflict (order_id, product_id) do update
set quantity = excluded.quantity,
    active = true,
    released_at = null;

-- A synchronization run writes to this private stage first. The publish RPC
-- applies the entire package set and advances last_successful_run_id inside
-- one PostgreSQL transaction, so readers see either the old complete snapshot
-- or the new complete snapshot and never a partially overwritten mixture.
create table if not exists public.canix_package_sync_stage
  (like public.canix_package_current including defaults including constraints);

alter table public.canix_package_sync_stage
  add constraint canix_package_sync_stage_pkey primary key (sync_run_id, package_id);

alter table public.canix_package_sync_stage enable row level security;
revoke all on table public.canix_package_sync_stage from anon, authenticated;
grant all on table public.canix_package_sync_stage to service_role;

-- Synchronization ownership is claimed under a row lock. A running claim is
-- never stolen automatically: this prevents a slow prior run from resuming
-- and overwriting packages belonging to a newer successful run. Operational
-- recovery of a genuinely abandoned run is an explicit administrator action.
create or replace function public.canix_claim_sync_run(
  p_run_id uuid,
  p_force boolean default false,
  p_fresh_seconds integer default 300
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_state public.canix_sync_state%rowtype;
  started_at timestamptz := now();
begin
  if p_run_id is null then raise exception 'A synchronization run ID is required'; end if;
  if p_fresh_seconds < 0 or p_fresh_seconds > 3600 then raise exception 'Invalid freshness window'; end if;

  select * into current_state
  from public.canix_sync_state
  where id = 1
  for update;

  if current_state.status = 'running' then
    return jsonb_build_object(
      'claimed', false,
      'reason', 'already_running',
      'lastStartedAt', current_state.last_started_at,
      'activeRunId', current_state.active_run_id
    );
  end if;
  if not p_force and current_state.last_successful_at is not null
    and current_state.last_successful_at > started_at - make_interval(secs => p_fresh_seconds) then
    return jsonb_build_object(
      'claimed', false,
      'reason', 'fresh',
      'lastSuccessfulAt', current_state.last_successful_at
    );
  end if;

  update public.canix_sync_state
  set status = 'running',
      active_run_id = p_run_id,
      last_started_at = started_at,
      last_error = null,
      updated_at = started_at
  where id = 1;

  return jsonb_build_object('claimed', true, 'runId', p_run_id, 'startedAt', started_at);
end;
$$;

create or replace function public.canix_publish_sync_run(
  p_run_id uuid,
  p_package_count integer,
  p_package_pages integer,
  p_sales_order_pages integer,
  p_latest_source_updated_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_state public.canix_sync_state%rowtype;
  staged_count integer;
  column_list text;
  update_list text;
  completed_at timestamptz := now();
begin
  if p_run_id is null then raise exception 'A synchronization run ID is required'; end if;
  if p_package_count < 0 or p_package_pages < 0 or p_sales_order_pages < 0 then
    raise exception 'Synchronization counters must be non-negative';
  end if;

  select * into current_state
  from public.canix_sync_state
  where id = 1
  for update;

  if current_state.status <> 'running' or current_state.active_run_id is distinct from p_run_id then
    raise exception 'Canix sync ownership was lost before snapshot publication';
  end if;

  select count(*) into staged_count
  from public.canix_package_sync_stage
  where sync_run_id = p_run_id;
  if staged_count <> p_package_count then
    raise exception 'The staged Canix package count does not match the completed fetch';
  end if;

  select
    string_agg(format('%I', column_name), ', ' order by ordinal_position),
    string_agg(format('%1$I = excluded.%1$I', column_name), ', ' order by ordinal_position)
      filter (where column_name <> 'package_id')
  into column_list, update_list
  from information_schema.columns
  where table_schema = 'public' and table_name = 'canix_package_current';

  execute format(
    'insert into public.canix_package_current (%1$s)
       select %1$s from public.canix_package_sync_stage where sync_run_id = $1
     on conflict (package_id) do update set %2$s',
    column_list,
    update_list
  ) using p_run_id;

  insert into public.canix_package_coa (
    package_id, canix_item_id, compliance_tag, document_url,
    source_document_id, lab_name, batch_number, tested_at, result_status,
    cannabinoids, terpenes, profile, source_updated_at, synced_at,
    source_payload
  )
  select
    package_id, item_id, tag, coa_url, coa_document_id, lab_name,
    lab_batch_number, lab_tested_at,
    coalesce(test_result_status, lab_test_status), cannabinoids, terpenes,
    lab_profile, source_updated_at, synced_at,
    jsonb_build_object(
      'coa_url', coa_url,
      'coa_document_id', coa_document_id,
      'lab_name', lab_name,
      'lab_batch_number', lab_batch_number,
      'lab_tested_at', lab_tested_at
    )
  from public.canix_package_current
  where sync_run_id = p_run_id
  on conflict (package_id) do update
  set canix_item_id = excluded.canix_item_id,
      compliance_tag = excluded.compliance_tag,
      document_url = excluded.document_url,
      source_document_id = excluded.source_document_id,
      lab_name = excluded.lab_name,
      batch_number = excluded.batch_number,
      tested_at = excluded.tested_at,
      result_status = excluded.result_status,
      cannabinoids = excluded.cannabinoids,
      terpenes = excluded.terpenes,
      profile = excluded.profile,
      source_updated_at = excluded.source_updated_at,
      synced_at = excluded.synced_at,
      source_payload = excluded.source_payload;

  delete from public.canix_package_current where sync_run_id <> p_run_id;

  update public.canix_sync_state
  set status = 'success',
      active_run_id = null,
      last_successful_run_id = p_run_id,
      last_completed_at = completed_at,
      last_successful_at = completed_at,
      latest_source_updated_at = p_latest_source_updated_at,
      package_count = p_package_count,
      package_pages = p_package_pages,
      sales_order_pages = p_sales_order_pages,
      last_error = null,
      updated_at = completed_at
  where id = 1;

  delete from public.canix_package_sync_stage;

  return jsonb_build_object(
    'published', true,
    'runId', p_run_id,
    'packages', p_package_count,
    'completedAt', completed_at
  );
end;
$$;

revoke all on function public.portal_commit_order_line_inventory() from public, anon, authenticated;
revoke all on function public.portal_release_terminal_inventory_commitments() from public, anon, authenticated;
revoke all on function public.portal_enforce_order_transition_graph() from public, anon, authenticated;
revoke all on function public.canix_claim_sync_run(uuid, boolean, integer) from public, anon, authenticated;
revoke all on function public.canix_publish_sync_run(uuid, integer, integer, integer, timestamptz) from public, anon, authenticated;
grant execute on function public.portal_commit_order_line_inventory() to service_role;
grant execute on function public.portal_release_terminal_inventory_commitments() to service_role;
grant execute on function public.portal_enforce_order_transition_graph() to service_role;
grant execute on function public.canix_claim_sync_run(uuid, boolean, integer) to service_role;
grant execute on function public.canix_publish_sync_run(uuid, integer, integer, integer, timestamptz) to service_role;

comment on table public.portal_inventory_commitment is
  'Portal-side count inventory commitments created atomically with order lines and released only by terminal/rejected order outcomes.';
comment on function public.canix_claim_sync_run(uuid, boolean, integer) is
  'Atomically claims the singleton Canix synchronization lease; automatic callers never steal a running lease.';
comment on function public.canix_publish_sync_run(uuid, integer, integer, integer, timestamptz) is
  'Atomically publishes a fully staged Canix snapshot, updates COAs, retires stale packages, and advances the successful-run pointer.';
