-- Synthetic executive-demo documents generated by urbanXtracts. These files
-- are visibly watermarked and never map to Canix, QuickBooks, or Monday.

update public.portal_brand_profile_detail as detail
set agreement_state = 'active',
    w9_state = 'approved',
    insurance_state = 'approved',
    payment_terms_state = 'approved',
    contacts_state = 'approved',
    product_approval_state = 'approved',
    updated_at = now()
from public.portal_organization as organization
where detail.organization_id = organization.id
  and organization.kind = 'brand'
  and organization.legal_name = 'Test Brand';

insert into public.portal_brand_document (
  organization_id, category, title, document_date, expires_on, visibility,
  status, notes, object_path, original_name, content_type, size_bytes, sha256,
  scan_state, scan_provider, uploaded_by_email
)
select organization.id, document.category, document.title, document.document_date,
  document.expires_on, 'brand_and_internal', 'current', document.notes,
  document.object_path, document.original_name, 'application/pdf',
  document.size_bytes, document.sha256, 'clean', 'generated-demo-artifact',
  'demo-system@urbanxtracts.com'
from public.portal_organization as organization
cross join (values
  ('license', 'Test Brand Operating License', date '2026-01-01', date '2027-12-31',
    'DEMO — synthetic license for executive review; not legally valid.',
    'test-brand/profile/license/134a4831b2845cfe9b177287c070d1a88f8e33feb5aa59eff6aecfb913facf28.pdf',
    'test-brand-operating-license.pdf', 2225,
    '134a4831b2845cfe9b177287c070d1a88f8e33feb5aa59eff6aecfb913facf28'),
  ('tax', 'Test Brand W-9', date '2026-01-01', null,
    'DEMO — synthetic tax form for executive review; not legally valid.',
    'test-brand/profile/tax/47b055a75e6bb8d043b450cdd85879b5dc663d4cc0b0263c8b395b541c7a7a9c.pdf',
    'test-brand-w9.pdf', 2223,
    '47b055a75e6bb8d043b450cdd85879b5dc663d4cc0b0263c8b395b541c7a7a9c'),
  ('brand_guidelines', 'Test Brand Brand Guidelines', date '2026-01-01', null,
    'DEMO — synthetic marketing guide for executive review.',
    'test-brand/profile/brand_guidelines/66c68f088a6ba7bdcabf741061737a3d6dba63fcf3aa2d12e993936e50f29e79.pdf',
    'test-brand-brand-guidelines.pdf', 2224,
    '66c68f088a6ba7bdcabf741061737a3d6dba63fcf3aa2d12e993936e50f29e79')
) as document(category, title, document_date, expires_on, notes, object_path,
  original_name, size_bytes, sha256)
where organization.kind = 'brand' and organization.legal_name = 'Test Brand'
on conflict (organization_id, category, sha256) do update set
  title = excluded.title,
  document_date = excluded.document_date,
  expires_on = excluded.expires_on,
  visibility = excluded.visibility,
  status = 'current',
  notes = excluded.notes,
  object_path = excluded.object_path,
  original_name = excluded.original_name,
  size_bytes = excluded.size_bytes,
  scan_state = 'clean',
  scan_provider = excluded.scan_provider,
  archived_at = null,
  updated_at = now();

insert into public.portal_brand_agreement (
  organization_id, requirement_code, agreement_type, reference, status,
  visibility, version_label, effective_on, expires_on, term_type,
  renewal_owner, renewal_notice_days, evidence_summary, document_reference,
  submitted_by_email, submitted_at, reviewed_by_email, reviewed_at,
  review_decision, published_at, terms_mode
)
select organization.id, 'msa', 'Master Service Agreement', 'TEST-BRAND-MSA-2026',
  'active', 'published', '1.0', date '2026-01-01', date '2027-12-31',
  'fixed_term', 'Operations', array[90, 60, 30, 0],
  'DEMO — synthetic executive-review agreement. Not a valid contract.',
  'test-brand/agreement/msa/4cbfb332590d360c183c6d120dabb742d5626cb34fbedd9bba8987361eaf65ad.pdf',
  'demo-system@urbanxtracts.com', now(), 'demo-system@urbanxtracts.com', now(),
  'approved', now(), 'metadata_only'
from public.portal_organization as organization
where organization.kind = 'brand' and organization.legal_name = 'Test Brand'
on conflict (organization_id, reference) do update set
  requirement_code = excluded.requirement_code,
  status = 'active',
  visibility = 'published',
  version_label = excluded.version_label,
  effective_on = excluded.effective_on,
  expires_on = excluded.expires_on,
  term_type = excluded.term_type,
  renewal_owner = excluded.renewal_owner,
  evidence_summary = excluded.evidence_summary,
  document_reference = excluded.document_reference,
  review_decision = 'approved',
  reviewed_by_email = excluded.reviewed_by_email,
  reviewed_at = now(),
  published_at = now(),
  updated_at = now();

insert into public.portal_brand_agreement_document (
  agreement_id, object_path, original_name, content_type, size_bytes, sha256,
  scan_state, scan_provider, uploaded_by_type, uploaded_by_email
)
select agreement.id,
  'test-brand/agreement/msa/4cbfb332590d360c183c6d120dabb742d5626cb34fbedd9bba8987361eaf65ad.pdf',
  'test-brand-master-service-agreement.pdf', 'application/pdf', 2238,
  '4cbfb332590d360c183c6d120dabb742d5626cb34fbedd9bba8987361eaf65ad',
  'clean', 'generated-demo-artifact', 'internal', 'demo-system@urbanxtracts.com'
from public.portal_brand_agreement as agreement
join public.portal_organization as organization on organization.id = agreement.organization_id
where organization.kind = 'brand' and organization.legal_name = 'Test Brand'
  and agreement.reference = 'TEST-BRAND-MSA-2026'
on conflict (agreement_id) do update set
  object_path = excluded.object_path,
  original_name = excluded.original_name,
  size_bytes = excluded.size_bytes,
  sha256 = excluded.sha256,
  scan_state = 'clean',
  scan_provider = excluded.scan_provider;
